= Eager beans

image:https://maven-badges.herokuapp.com/maven-central/io.github.lumnitzf/eager-beans/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/io.github.lumnitzf/eager-beans"]
image:https://travis-ci.com/LumnitzF/eager-beans.svg?branch=master["Build Status", link="https://travis-ci.com/LumnitzF/eager-beans"]
image:https://coveralls.io/repos/github/LumnitzF/eager-beans/badge.svg?branch=master["Coverage", link="https://coveralls.io/github/LumnitzF/eager-beans?branch=master"]

Provides a CDI extension for defining eager initialized beans.

== Dependency

The dependency is available on maven central.
To include it in your project simply add it to your dependencies:

[source,xml]
----
<dependency>
    <groupId>io.github.lumnitzf</groupId>
    <artifactId>eager-beans</artifactId>
    <version>${eager-beans.version}</version>
</dependency>
----

== How it works

To mark a bean as eager initialized simply annotate it as `@Eager`.
An eager bean must not have scope `@Dependent`.

[source,java]
----
import javax.enterprise.context.RequestScoped;
import javax.annotation.PostConstruct;
import io.github.lumnitzf.eagerbeans.Eager;

@Eager
@RequestScoped
public class EagerBean {

    @PostConstruct
    void init() {
        System.out.println("Bean initialized");
    }
}
----

In this example, as soon as the request scope is initialized the bean will also be initialized, triggering the `@PostConstruct` annotated method.

The initialization will be triggered by calling the `toString()` method of the bean.
If this behavior is not desired (e.g. toString triggers other lazy beans) the bean may implement `EagerInitializable`.
The initialization will then be triggered by using the no-op method `EagerInitializable::init`.

[source,java]
----
import javax.enterprise.context.RequestScoped;
import javax.annotation.PostConstruct;
import io.github.lumnitzf.eagerbeans.Eager;
import io.github.lumnitzf.eagerbeans.EagerInitializable;

@Eager
@RequestScoped
public class EagerBean implements EagerInitializable {

    @PostConstruct
    void init() {
        System.out.println("Bean initialized");
    }

    @RequestScoped
    public String toString() {
        // expensive computation
    }
}
----
